fix: social media and focus in footer links
Binlandorg/binland-website-client pull request #149
Opened 2024-05-21 04:42 UTC by GustavoUT22

2024-05-21 12:21 UTC, Mardecera commented
Focus behavior is inappropriate, it paints an additional black line. And the design of the focus on the `network buttons` does not match that of `Figma`.

![Captura de pantalla 2024-05-21 071839](https://github.com/Binlandorg/EnterpriseLandingPage/assets/18353569/fabc6cee-3797-4759-b8ea-d97b9b677511)  ![Captura de pantalla 2024-05-21 071752](https://github.com/Binlandorg/EnterpriseLandingPage/assets/18353569/cc300136-3d18-44c5-adef-3ea025b5c128)

2024-05-21 12:23 UTC, Mardecera requested changes
Focus behavior is inappropriate, it paints an additional black line. And the design of the focus on the `network buttons` does not match that of `Figma`.

![Captura de pantalla 2024-05-21 071839](https://github.com/Binlandorg/EnterpriseLandingPage/assets/18353569/5620a147-3eec-4e01-b11d-d815af26f272)  ![Captura de pantalla 2024-05-21 071752](https://github.com/Binlandorg/EnterpriseLandingPage/assets/18353569/bc6a9739-1eb5-409c-aef8-ae9b969fdb30)

2024-05-22 18:01 UTC, Mardecera commented on src/components/SocialMedia/SocialMedia.tsx
>      to: 'twitter.com/binland_dev',
@BinlandDev

2024-05-22 18:02 UTC, Mardecera commented on src/components/SocialMedia/SocialMedia.tsx
> +const socialLinksIcons: ILinks[] = [
Singular ILink

2024-05-22 18:24 UTC, GustavoUT22 commented on src/components/SocialMedia/SocialMedia.tsx
> +const socialLinksIcons: ILinks[] = [
done

2024-05-22 18:24 UTC, GustavoUT22 commented on src/components/SocialMedia/SocialMedia.tsx
>      to: 'twitter.com/binland_dev',
done

2024-05-22 19:25 UTC, Mardecera approved these changes
Nice!

2024-05-23 18:45 UTC, CrhistianT7 approved these changes
LGTM!!

2024-05-23 19:27 UTC, merged