Styles(VerticalTabsAndSelect): add hover and active color correctly and fix little bug about border radius
Binlandorg/binland-website-client pull request #170
Opened 2024-09-11 23:46 UTC by GustavoUT22

# Fix styles about verticaltabs and select

## Summary
This PR addresses style fixes for the select component in the mobile version and adjustments to the border-top-left-radius for verticaltabs.

## Problem

Incorrect hover and active colors for the select component in mobile view.
border-top-left-radius in verticaltabs not rendering as expected on mobile devices.
## Cause
Hover and active state styles were not optimized for mobile-specific scenarios.
The border-top-left-radius worked well on larger screens but did not adapt correctly to mobile view.
## Solution
Updated the hover and active color styles for the select component to ensure proper appearance in mobile view.
Adjusted the border-top-left-radius for verticaltabs to function as expected on both desktop and mobile views.

## Type of change

- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update
- [ ] Refactor
- [X] Styling
- [ ] Testing
- [ ] Chore
- [ ] Other: ...

## Checklist:

These items must be completed before the code review

- [X] Check that branch is pointing to production environment
- [X] Remove console.logs
- [X] Check imports format
- [X] Check variables destructure
- [X] Check docs
- [X] Review the entire pull request yourself before sending it to the reviewer
- [X] Check task requirements on Monday or Sprint Planning sheet

## Screenshots or Gifs

2024-09-15 14:32 UTC, mardecera requested changes
![image](https://github.com/user-attachments/assets/f10ab9aa-7e80-4715-8e72-6f9036b5908a)

Select options are above select.

2024-09-15 14:46 UTC, CrhistianT7 requested changes

2024-09-15 14:46 UTC, CrhistianT7 commented on src/ui/Select/Select.styles.ts
> +      $type == 'primary' ? `` : `${colors.tertiary.hover[600]}`};
use secondary type to make the ternary expression

2024-09-15 14:46 UTC, CrhistianT7 commented on src/ui/Select/Select.styles.ts
> +      $type == 'primary' ? `` : `${colors.tertiary.active[700]}`};
use secondary type to make the ternary expression

2024-09-20 00:17 UTC, mardecera approved these changes
Nice

2024-09-20 03:02 UTC, merged